#!/usr/bin/env bash
# Create local-only credentials for Mission Control (idempotent; never overwrites).
#   .env                              adapter settings (MC_URL, MC_API_KEY, ...)
#   vendor/mission-control/.env       Mission Control settings (admin user, API key)
#   vendor/hermes-synapse/.env        copied from infra/hermes.env
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

rand() { openssl rand -hex "$1"; }

if [[ ! -f .env ]]; then
  cat > .env <<EOF
# Agent RTS local settings (gitignored). Generated by scripts/gen-env.sh.
ADAPTER_SOURCE=hermes
ADAPTER_PORT=8770
ADAPTER_COST_BUDGET_USD=0.50
HERMES_URL=http://127.0.0.1:8100
HERMES_TOKEN=dev_master_token
MC_URL=http://127.0.0.1:3000
MC_API_KEY=$(rand 24)
MC_ADMIN_USER=admin
MC_ADMIN_PASS=$(rand 12)
EOF
  chmod 600 .env
  echo "created .env"
fi

set -a; source .env; set +a

if [[ -d vendor/mission-control && ! -f vendor/mission-control/.env ]]; then
  cat > vendor/mission-control/.env <<EOF
# Generated by agent-rts/scripts/gen-env.sh. Local use only.
PORT=3000
AUTH_USER=$MC_ADMIN_USER
AUTH_PASS=$MC_ADMIN_PASS
API_KEY=$MC_API_KEY
AUTH_SECRET=$(rand 32)
NEXT_PUBLIC_GATEWAY_OPTIONAL=true
MC_COORDINATOR_AGENT=
MC_DISABLE_RATE_LIMIT=1
MC_DISABLE_RUNTIME_SCAN=1
# Local Ollama models are free: report them at zero cost.
MC_SUBSCRIBED_PROVIDERS=ollama
EOF
  chmod 600 vendor/mission-control/.env
  echo "created vendor/mission-control/.env"
fi

if [[ -d vendor/hermes-synapse ]]; then
  cp infra/hermes.env vendor/hermes-synapse/.env
fi
